config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get 'articles/index'

  get 'styles/index'

  get 'sessions/new'

  resources :products

  resources :styles

  resources :articles

  root 'sessions#new'

  get      '/login',  to: 'sessions#new'
  post     '/login',  to: 'sessions#create'
  delete   '/logout', to: 'sessions#destroy'
end

app/models/style.rb
class Style < ApplicationRecord

    default_scope -> { order(created_at: :desc) }
    validates :caption,   presence: true, length:{ maximum: 50}
    validates :price,  length:{ maximum: 20}, format: /\A[0-9]+\z/

    validates :picture, presence: true
    mount_uploader :picture, StylePictureUploader
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController

    before_action :logged_in_user, only: [:new,:create,:edit,:update,:destroy]

    def index
      @style = Style.new
      @styles = Style.all.paginate(page: params[:page], per_page: 9)
    end

    def new
      @style = Style.new
    end

    def create
      @style = Style.new(style_params)
      if @style.save
        @styles = Style.all.paginate(page: params[:page], per_page: 9)
      else
        render 'new'
      end
    end

    def edit
      @style = Style.find(params[:id])
    end

    def update
      @style = Style.find(params[:id])
      if @style.update_attributes(style_params)
        @styles = Style.all.paginate(page: params[:page], per_page: 9)
      else
        render 'edit'
      end
    end

    def destroy
      Style.find(params[:id]).destroy
      redirect_to styles_url
    end

    private

    def style_params
      params.require(:style).permit(:caption, :price,
                                  :picture)
    end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_edit_form_js.html.erb
<% provide(:button_text, '編集を保存') %>

<div class="js-form-close"><i class="fa fa-times-circle"></i></div>
<div class="wrapper">
    <h1 class="form-title">スタイル編集</h1>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
    <%= form_for(@style,remote: true) do|f| %>

    <%= render'shared/error_messages',object: f.object %>

    <div class="form-group">
        <%= f.label "タイトル" %>
        <%= f.text_field :caption ,class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label "値段" %>
        <%= f.text_field :price ,class: 'form-control' %>
    </div>

     <%= f.label '画像' %>

      <div id="img_field">
          <span class="form-preview"><%= image_tag(@style.picture)%><span>
      </div>

    <%= f.submit yield(:button_text), class: "submit-btn" %>
    <% end %>
    </div>
    </div>
</div>

app/views/styles/_edit_icons.html.erb
<% if logged_in? %>
<div class="edit-icons">
    <%= link_to edit_style_path(object),remote: true do%>
    <i class="fa fa-edit"></i>
    <% end %>
    <%= link_to object, method: :delete, data:{confirm:"こちらの投稿を削除しますか？"} do %>
    <i class="fa fa-trash"></i>
    <% end %>
</div>
<% end %>

app/views/styles/_new_form_js.html.erb
<% provide(:button_text, '投稿する') %>

<div class="js-form-close"><i class="fa fa-times-circle"></i></div>
<div class="wrapper">
    <h1 class="form-title">スタイル新規投稿</h1>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
    <%= form_for(@style,remote: true) do|f| %>

    <%= render'shared/error_messages',object: f.object %>

    <div class="form-group">
        <%= f.label "タイトル" %>
        <%= f.text_field :caption ,class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label "値段" %>
        <%= f.text_field :price ,class: 'form-control' %>
    </div>

     <%= f.label '画像' %>

      <div id="img_field" onClick="$('#file').click()" >
        <% if @style.picture.present? %>
          <%= image_tag(@style.picture) %>
        <% else %>
          <i class="fa fa-image"></i>
        <% end %>
      </div>
    <%= f.file_field :picture, class: "image", style: "display:none;", id: "file",
                               accept: 'image/jpeg,image/gif,image/png'%>

    <%#<%= f.hidden_field :picture_cache %>

    <%= f.submit yield(:button_text), class: "submit-btn" %>
    <% end %>
    </div>
    </div>
</div>

app/views/styles/_style.html.erb
<div class="item">
    <a class="js-modal-open" data-target="modal-<%= style.id %>">
    <%= image_tag style.picture %>
    </a>
</div>

<div id="modal-<%= style.id %>" class="modal js-modal">
    <div class="modal-bg js-modal-close"></div>
    <div class="modal-content">
        <div class="close-btn js-modal-close"><i class="fa fa-times-circle"></i></div>
        <%= image_tag style.picture %>
        <h1><%= style.caption %><h1>
        <p class="price">¥<%= style.price %></p>
        <%= render 'styles/edit_icons', object: style %>
    </div>
</div>

app/views/styles/create.js.erb
$(".grid").html("<%= escape_javascript(render(@styles)) %>");
$("#new-form").removeClass("active");
$(document).ready(function(){
    bodyRemoveFixed();
    modalDisplay();
});

    var msg = "投稿が完了しました"
    postSuccessMsg(msg);
    postBtnUp();

app/views/styles/edit.js.erb
 $("#edit-form").html("<%= escape_javascript(render('styles/edit_form_js')) %>");
 $("#edit-form").addClass('active');
 $(document).ready(function(){
    editFormClose();

    formImageThumb();
});

app/views/styles/index.html.erb
<% provide(:title, 'Style') %>
<% provide(:new, new_style_path) %>
<%= stylesheet_link_tag 'common.css' %>
<%= stylesheet_link_tag 'styles.css' %>
<%= stylesheet_link_tag 'form.css' %>

    <div class="p-header">
        <div id="style">
                <%= render 'layouts/header_p'%>
        </div>
    </div><!--p-header-->
    <div class="m-header-nav">
        <%= render 'layouts/header_m'%>
        <%= render 'layouts/header_nav_m'%>
    </div>

    <h2 class="page-title"><span>-</span> Style <span>-</span></h2>

    <div class="wrapper">

    <%= image_tag 'style/top-image.png' ,class: 'top-image' %>
    </div>

    <p class="post-explain-text">下の画像をクリックするとスタイルの詳細がモーダルウィンドウで表示</p>
    <p class="post-explain-text">ログイン時、モーダルにコンテンツの編集、削除アイコンが表示されます。</p>
    <p class="post-explain-text">ログイン時、左下の<span></span>のボタンは、新規投稿ボタンです。</p>

    <div class="style-contents">
    <% if @styles %>
        <div class="grid">
            <%= render @styles %>
        </div>
        <%= will_paginate @styles, previous_label: '<', next_label: '>', inner_window: 1 %>
    </div>
    <% end %>

    <% if logged_in? %>
    <%= render 'layouts/new_btn'%>

    <div id="new-form">
    <%= render 'styles/new_form_js' %>
    </div>
    <div id="edit-form">
    <%= render 'styles/edit_form_js' %>
    </div>

    <div id="post-success-msg"></div>
    <% end %>



<%= javascript_include_tag "common.js" %>
<%= javascript_include_tag "style.js" %>

app/views/styles/new.js.erb
 $("#new-form").html("<%= escape_javascript(render('styles/new_form_js')) %>");
 $("#new-form").addClass('active');
 $(document).ready(function(){
    bodyFixed();

    newFormClose();

    formImageThumb();
});

app/views/styles/update.js.erb
$(".grid").html("<%= escape_javascript(render(@styles)) %>");
$("#edit-form").removeClass("active");
$(document).ready(function(){
    bodyRemoveFixed();
    modalDisplay();
});
    var msg = "編集を保存しました"
    postSuccessMsg(msg);
    postBtnUp();