config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get 'articles/index'

  get 'styles/index'

  get 'sessions/new'

  resources :products

  resources :styles

  resources :articles

  root 'sessions#new'

  get      '/login',  to: 'sessions#new'
  post     '/login',  to: 'sessions#create'
  delete   '/logout', to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="contents">
        <div class="shop-info">
            <h1>Shop Info</h1>
            <p>
                〒○○-○○○○<br>
                ○○県××市△△町123−456<br>
                <br>
                TEL ××××-××-××××<br>
                <br>
                OPEN 9:00~1800<br>
            </p>
        </div>
        <div class="line-officail">
            <h1>SNS official account</h1>
            <div class="line-btn"><a href="#">Add Account</a></div>
            <p><span>(サービスや商品の情報を発信します。)</span></p>
        </div>
    </div>
    <div class="copyright">
        <p><small>&copy; 2019 sample美容室</small></p>
        <p><small>Designed By Ryo10Leo</small></p>
    </div>
</footer><!--footer-->

app/views/layouts/_header_m.html.erb
<header class="page-header wrapper">
    <h1>
        <%= image_tag 'shared/sample-logo.png' ,class: 'logo' %>
    </h1>
    <div class="menu-trigger" href="#">
            <span></span>
            <span></span>
            <span></span>
    </div>
</header><!--page-header wrapper-->

app/views/layouts/_header_nav_m.html.erb
<nav>
    <ul class="main-nav">
        <li><%= link_to 'News', articles_path %></li>
        <li><%= link_to 'Style', styles_path %></li>
        <li><%= link_to 'Product', products_path %></li>
        <% if logged_in? %>
        <li>
            <%= link_to "Log out", logout_path, method: :delete %>
        </li>
        <% else %>
         <li>
            <%= link_to "Log in", login_path %>
        </li>
        <% end %>
    </ul><!--main-nav-->
</nav>

app/views/layouts/_header_p.html.erb
<header class="page-header wrapper">
    <h1>
        <%= image_tag 'shared/sample-logo.png' ,class: 'logo' %>
    </h1>
    <nav>
        <ul class="main-nav">
            <li><%= link_to 'News', articles_path  %></li>
            <li><%= link_to 'Style', styles_path %></li>
            <li><%= link_to 'Product', products_path %></li>
             <% if logged_in? %>
            <li>
                <%= link_to "Log out", logout_path, method: :delete %>
            </li>
            <% else %>
            <li>
                <%= link_to "Log in", login_path %>
            </li>
            <% end %>
        </ul><!--main-nav-->
    </nav>
</header><!---page-header wapper-->

app/views/layouts/_new_btn.html.erb
<p id="new-btn">
    <%= link_to yield(:new), remote: true do %>
        <i class="fa fa-plus"></i>
    <% end %>
</p>

app/views/layouts/_page_top_btn.html.erb
<p id="pageTop"><a href="#"><i class="fa fa-chevron-up"></i></a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="uft-8">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="desctiption" content="ratio美容室の公式HPです。福井県福井市">
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag('favicon.ico') %>
    <%= favicon_link_tag('apple-touch-icon-180x180.png',
                     {:rel => 'apple-touch-icon',
                      :sizes => '180x180',
                      :type => 'image/png'}) %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= include_gon %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/footer'%>
    <%= render 'layouts/page_top_btn' %>
  </body>
</html>